app:
  name: 'postgres_to_kafka_loader'
  version: '1.0.0'

kafka:
  host: 'localhost'
  port: '9092'
  topic: 'profiles'

postgres:
  host: '172.17.0.2'
  port: '5432'
  user: 'postgres'
  password: 'postgres'
  dbname: 'postgres'
  sslmode: 'disable'